### ISSUE TITLE
No longer functions as intented

### ISSUE THREAD

**Issue by ComfyChloe** [kThisIsCvpv/rl-help#1]
Will alwasy end up with a invaild flag error, I've tried to resolve the issue myself but no progress.

![image](https://user-images.githubusercontent.com/22899721/218437878-c71f58b1-2d09-4cfb-93cb-2a57bc50e510.png)

**Comment by kThisIsCvpv** [comment]
It doesn't look like your maven is properly configured to run the right goals.

At the top right, could you show me your maven run configurations?

![image](https://user-images.githubusercontent.com/6757526/218490239-e500124c-a562-4d1c-ae42-40cf33d6d874.png)

**Comment by ComfyChloe** [comment]
After testing again, It turns out when I created the project it was forced onto SDK 1.8 not SDK 11, which has fixed the issue.
![image](https://user-images.githubusercontent.com/22899721/218505613-a7fb7e8f-d20e-4e40-8009-d51f40561a8a.png)
Thank you:)
